name: Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ready-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version-file: .github/workflows/.ci-java-version
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - name: Check with Gradle
        run: ./gradlew check
