name: Check

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [ main ]
    tags: [ 'v*' ]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version-file: .github/workflows/.ci-java-version

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: check
