name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version-file: .github/workflows/.ci-java-version
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish artifacts
        run: ./gradlew :publishToSonatype :closeAndReleaseSonatypeStagingRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.SIGNING_KEY_ID}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.SONATYPE_USERNAME}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.SONATYPE_PASSWORD}}
