name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GRADLE_UPDATE_PAT }}

